# Generated by Django 5.1.3 on 2024-12-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
